title: <p align="center"> Vidhya Subramanian</p>
logo: /assets/img/Vidhya Subramanian_2021-smalll.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vidhya-s/">LinkedIn</a> |
  <a href="https://github.com/vidhi2202">GitHub</a>
  
  <br>   
  I'm a full stack with 13+ years industry experience.
  <br>
  </p>



theme: jekyll-theme-minimal